/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#4A6163',
          50:  '#F9FAF4',
          100: '#FFF6E8',
          200: '#FFE4CF',
          300: '#FFC94B',
          400: '#4A6163',
          500: '#FFC94B',
          600: '#F9A66C',
          700: '#F17A7E',
          800: '#4A6163',
          900: '#263E40',
          dark: '#4A6163',
        },
        secondary: {
          DEFAULT: '#F17A7E',
          500: '#F17A7E',
          600: '#F9A66C',
          dark: '#4A6163',
        },
        dark: {
          bg:        '#F9FAF4',
          surface:   '#FFF6E8',
          container: '#FFE4CF',
          high:      '#FFC94B',
          highest:   '#F9A66C',
          border:    '#4A6163',
          text:      '#263E40',
          muted:     '#5E7375',
        },
        surface: {
          DEFAULT:   '#F9FAF4',
          container: '#FFF6E8',
          high:      '#FFE4CF',
          highest:   '#FFC94B',
        },
        'on-surface': '#263E40',
        outline: '#4A6163',
        success: '#65A879',
        warning: '#FFC94B',
        error:   '#F17A7E',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label':   ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        'sm':   '4px',
        DEFAULT:'8px',
        'md':   '12px',
        'card': '16px',
        'hero': '24px',
        'pill': '9999px',
      },
      boxShadow: {
        'lvl1': '4px 4px 0 #4A6163',
        'lvl2': '6px 6px 0 #4A6163',
        'lvl3': '8px 8px 0 #4A6163',
      },
      backgroundImage: {
        'gradient-primary': 'none',
        'gradient-dark':    'none',
        'gradient-card':    'none',
        'hero-mesh':        'none',
      },
      animation: {
        'fade-in':    'fadeIn 0.5s ease-out',
        'slide-up':   'slideUp 0.5s ease-out',
        'slide-in-left': 'slideInLeft 0.4s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'float':      'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:      { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp:     { from: { opacity: 0, transform: 'translateY(20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideInLeft: { from: { opacity: 0, transform: 'translateX(-20px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        float:       { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
      },
      spacing: {
        '18': '4.5rem',
        '72': '18rem',
        '80': '20rem',
        '88': '22rem',
        '96': '24rem',
      },
    },
  },
  plugins: [],
}
